# Generated by Django 2.1.7 on 2019-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=50, verbose_name='Название  меню')),
                ('url', models.CharField(help_text='Ссылка, например /about/ или http://foo.com/', max_length=100)),
                ('group', models.ManyToManyField(to='auth.Group', verbose_name='Группа доступа')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'permissions': (('menu_view', 'can view menu'),),
            },
        ),
    ]
