# Generated by Django 2.1.7 on 2019-02-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_service', models.DateField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True)),
                ('type_of_service', models.CharField(choices=[('OF', 'Работа в офисе'), ('RM', 'Удаленная работа'), ('TP', 'Выездная работа')], default='OF', max_length=2)),
                ('product', models.CharField(choices=[('SV', 'Сервис и настройки')], default='SV', max_length=2)),
                ('incident', models.CharField(blank=True, max_length=100, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to=None)),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('CS', 'Закрыт'), ('RL', 'Отказ'), ('IW', 'В работе')], default='NW', max_length=2)),
                ('bill', models.CharField(max_length=100)),
                ('kkt_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('namber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('applications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Applications')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100000, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Applications')),
                ('name', models.ManyToManyField(to='applications.Service')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='applications.Company'),
        ),
        migrations.AddField(
            model_name='applications',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applications',
            name='kkt',
            field=models.ManyToManyField(to='applications.Kkt'),
        ),
        migrations.AddField(
            model_name='applications',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applications',
            name='service',
            field=models.ManyToManyField(to='applications.Service'),
        ),
    ]
