# Generated by Django 2.1.7 on 2019-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d'),
        ),
    ]
