# Generated by Django 2.1.7 on 2019-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20190219_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='file/self.id'),
        ),
    ]
