# Generated by Django 2.1.7 on 2019-02-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190219_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='file/{self.id}'),
        ),
    ]
