# Generated by Django 2.1.7 on 2019-02-19 12:40

from django.db import migrations, models
import help.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190219_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=help.applications.models.user_directory_path),
        ),
    ]
